ALTER TABLE "Outfit" ADD COLUMN "stickerOffsetX" REAL NOT NULL DEFAULT 0;
ALTER TABLE "Outfit" ADD COLUMN "stickerOffsetY" REAL NOT NULL DEFAULT 0;
ALTER TABLE "CalendarEntry" ADD COLUMN "stickerOffsetX" REAL NOT NULL DEFAULT 0;
ALTER TABLE "CalendarEntry" ADD COLUMN "stickerOffsetY" REAL NOT NULL DEFAULT 0;
