"use client";

import { ArrowLeft, CalendarPlus, ChevronLeft, ChevronRight, Download, Save, Trash2, Upload } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { BackgroundPicker, BackgroundStepper, StickerStage } from "@/components/background/background-controls";
import { apiFetch, fileToDataUrl } from "@/lib/client-api";
import { downloadImage } from "@/lib/download-image";
import { getBackgroundPreset, type BackgroundSettings } from "@/lib/backgrounds";
import type { CalendarItem } from "@/lib/types";
import { DatePickerModal } from "@/components/modals/date-picker-modal";
import { AddChoiceModal } from "@/components/modals/add-choice-modal";
import { DEFAULT_BACKGROUND_SETTINGS } from "@/lib/backgrounds";
import type { Look } from "@/lib/types";

export function CalendarOutfitDetail({ entry, settings, close, remove, changeDate, onChange }: { entry: CalendarItem; settings: BackgroundSettings; close?: () => void; remove?: () => void; changeDate?: (direction: -1 | 1) => void; onChange?: (settings: BackgroundSettings) => void }) {
  const router = useRouter();
  const uploadRef = useRef<HTMLInputElement>(null);
  const saveTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const [localSettings, setLocalSettings] = useState(settings);
  const [message, setMessage] = useState(""); const [dateOpen, setDateOpen] = useState(false); const [sticker, setSticker] = useState(entry.outfit.generationStatus === "GENERATING" ? "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" : (entry.outfit.sticker ?? entry.outfit.image));
  const [addOpen, setAddOpen] = useState(false); const [wardrobeOpen, setWardrobeOpen] = useState(false); const [wardrobe, setWardrobe] = useState<Look[]>([]);
  const saveToDate = async (date: string) => { try { await apiFetch("/api/calendar", { method: "POST", body: JSON.stringify({ outfitId: String(entry.outfit.id), date, ...localSettings }) }); setDateOpen(false); setMessage("已另存到日历"); } catch { setMessage("保存失败"); } }; const saveToWardrobe = async () => { try { await apiFetch(`/api/outfits/${entry.outfit.id}`, { method: "PATCH", body: JSON.stringify({ savedToWardrobe: true }) }); setMessage("已保存到衣橱"); } catch (error) { setMessage(error instanceof Error ? error.message : "保存失败"); } };
  const dateLabel = (() => { const d = new Date(`${entry.date}T00:00:00`); return `${d.getFullYear()}年${d.getMonth()+1}月${d.getDate()}日 · 星期${"日一二三四五六"[d.getDay()]}`; })();
  const navigateDate = (direction: -1 | 1) => {
    const date = new Date(`${entry.date}T00:00:00`);
    date.setDate(date.getDate() + direction);
    const nextDate = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
    router.push(`/calendar/${nextDate}`);
  };
  const goBack = () => { close?.(); router.push("/calendar"); }; const removeEntry = async () => { if (remove) return remove(); await apiFetch(`/api/calendar/${entry.id}`, { method: "DELETE" }); router.push("/calendar"); };
  const save = (next: BackgroundSettings) => { setLocalSettings(next); onChange?.(next); if (saveTimer.current) clearTimeout(saveTimer.current); saveTimer.current = setTimeout(() => { void apiFetch(`/api/calendar/${entry.id}`, { method: "PATCH", body: JSON.stringify(next) }).catch(() => setMessage("保存失败")); }, 250); };
  const saveNow = (next: BackgroundSettings) => { setLocalSettings(next); onChange?.(next); if (saveTimer.current) clearTimeout(saveTimer.current); void apiFetch(`/api/calendar/${entry.id}`, { method: "PATCH", body: JSON.stringify(next) }).catch(() => setMessage("保存失败")); };
  useEffect(() => () => { if (saveTimer.current) clearTimeout(saveTimer.current); }, []);
  const uploadNew = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; try { const image = await fileToDataUrl(file); const created = await apiFetch<{ outfit: Look }>("/api/outfits", { method: "POST", body: JSON.stringify({ finalImage: image, stickerImage: image, source: "LOCAL_UPLOAD" }) }); setSticker(created.outfit.sticker ?? created.outfit.image); await apiFetch("/api/calendar", { method: "POST", body: JSON.stringify({ outfitId: String(created.outfit.id), date: entry.date, ...localSettings }) }); setMessage("贴纸已上传并保存，可移动和缩放"); } catch (e) { setMessage(e instanceof Error ? e.message : "上传失败"); } event.target.value = ""; };
  const openWardrobe = async () => { try { const data = await apiFetch<{ outfits: Look[] }>("/api/outfits"); setWardrobe(data.outfits); setAddOpen(false); setWardrobeOpen(true); } catch (e) { setMessage(e instanceof Error ? e.message : "衣橱加载失败"); } };
  const replaceFromWardrobe = async (look: Look) => { try { await apiFetch("/api/calendar", { method: "POST", body: JSON.stringify({ outfitId: String(look.id), date: entry.date, backgroundImage: look.background, backgroundKey: look.backgroundKey, stickerScale: look.stickerScale }) }); setWardrobeOpen(false); router.refresh(); } catch (e) { setMessage(e instanceof Error ? e.message : "替换失败"); } };
  const download = async () => { if (localSettings.backgroundKey === "none") return downloadImage(sticker, `fitcheck-${entry.date}`); const stage = document.querySelector(".calendar-detail .sticker-stage") as HTMLElement | null; const box = stage?.querySelector(".sticker-box") as HTMLElement | null; if (!stage || !box) throw new Error(); const scaleOut = 2; const canvas = document.createElement("canvas"); canvas.width = stage.clientWidth * scaleOut; canvas.height = stage.clientHeight * scaleOut; const ctx = canvas.getContext("2d"); if (!ctx) throw new Error(); const load = (src: string) => new Promise<HTMLImageElement>((resolve, reject) => { const image = new Image(); image.onload = () => resolve(image); image.onerror = reject; image.src = src; }); const preset = getBackgroundPreset(localSettings.backgroundKey); const bg = localSettings.backgroundKey === "custom" ? localSettings.backgroundImage : preset.asset; if (bg) { const image = await load(bg); const ratio = Math.max(canvas.width / image.naturalWidth, canvas.height / image.naturalHeight); const w = image.naturalWidth * ratio; const h = image.naturalHeight * ratio; ctx.drawImage(image, (canvas.width - w) / 2, (canvas.height - h) / 2, w, h); } else { ctx.fillStyle = localSettings.backgroundKey === "white" ? "#fff" : preset.fallback; ctx.fillRect(0, 0, canvas.width, canvas.height); } const image = await load((box.querySelector("img") as HTMLImageElement)?.currentSrc || sticker); const sr = stage.getBoundingClientRect(); const br = box.getBoundingClientRect(); ctx.drawImage(image, (br.left - sr.left) * scaleOut, (br.top - sr.top) * scaleOut, br.width * scaleOut, br.height * scaleOut); await downloadImage(canvas.toDataURL("image/png"), `fitcheck-${entry.date}`); };
  const originals: Array<{ src?: string; label: string }> = entry.outfit.source === "LOCAL_UPLOAD" ? [{ label: "本地上传图片" }] : [entry.outfit.person ? { src: entry.outfit.person, label: "人物" } : null, entry.outfit.garment ? { src: entry.outfit.garment, label: "服装" } : null].filter((item): item is { src: string; label: string } => Boolean(item));
  return <section className="calendar-detail"><div className="calendar-detail-date"><button aria-label="前一天" onClick={() => navigateDate(-1)}><ChevronLeft /></button><strong>{dateLabel}</strong><button aria-label="后一天" onClick={() => navigateDate(1)}><ChevronRight /></button></div><div className="outfit-detail-layout"><div className="outfit-detail-stage"><StickerStage interactive containBackground trimSticker={false} sticker={sticker} settings={localSettings} onSettingsChange={save}><BackgroundStepper value={localSettings} onChange={saveNow} /></StickerStage></div><aside className="outfit-detail-side"><div className="outfit-detail-actions"><button className="detail-side-btn" onClick={goBack}><ArrowLeft size={17} />返回</button><button className="detail-side-btn danger" onClick={() => void removeEntry()}><Trash2 size={17} />删除</button><BackgroundPicker value={localSettings} onChange={saveNow} onUpload={() => {}} /><button className="detail-side-btn" onClick={() => void download().catch(() => setMessage("下载失败"))}><Download size={17} />下载图片</button><button className="detail-side-btn" onClick={() => setAddOpen(true)}><Upload size={17} />添加穿搭</button><button className="detail-side-btn" onClick={() => void saveToWardrobe()}><Save size={17} />保存到衣橱</button><button className="detail-side-btn primary" onClick={() => setDateOpen(true)}><CalendarPlus size={17} />添加到日历</button></div><input ref={uploadRef} hidden type="file" accept="image/*" onChange={uploadNew} /><div className="outfit-originals">{originals.map((item) => <div className="outfit-original-item" key={item.label}>{item.src && <img src={item.src} alt={item.label} />}<span>{item.label}</span></div>)}</div>{message && <p className="result-message">{message}</p>}</aside></div>{dateOpen && <DatePickerModal close={() => setDateOpen(false)} confirm={(date) => void saveToDate(date)} />}{addOpen && <AddChoiceModal close={() => setAddOpen(false)} startTry={() => router.push("/try")} uploadImage={(event) => { void uploadNew(event); setAddOpen(false); }} chooseWardrobe={() => void openWardrobe()} />}{wardrobeOpen && <div className="overlay"><div className="choice-modal wardrobe-choice-modal"><button className="icon-close" onClick={() => setWardrobeOpen(false)}>×</button><h2>从衣橱中选择</h2><div className="wardrobe-choice-grid">{wardrobe.length ? wardrobe.map((look) => <button className="wardrobe-choice-card" key={look.id} onClick={() => void replaceFromWardrobe(look)}><StickerStage containBackground trimSticker={false} sticker={look.sticker ?? look.image} settings={{ ...DEFAULT_BACKGROUND_SETTINGS, backgroundKey: look.backgroundKey ?? "none", backgroundImage: look.background }} /><span>{look.date}</span></button>) : <p>衣橱中暂无可用穿搭</p>}</div></div></div>}</section>;
}
