"use client";
import { ArrowLeft, CalendarPlus, ChevronLeft, ChevronRight, Download, Trash2, Upload } from "lucide-react";
import { useRouter } from "next/navigation";
import { useRef, useState } from "react";
import { BackgroundPicker, BackgroundStepper, StickerStage } from "@/components/background/background-controls";
import { apiFetch, fileToDataUrl } from "@/lib/client-api";
import { DEFAULT_BACKGROUND_SETTINGS, type BackgroundSettings } from "@/lib/backgrounds";

export function EmptyCalendarDetail({ date }: { date: string }) {
  const router = useRouter(); const input = useRef<HTMLInputElement>(null); const [message, setMessage] = useState(""); const [settings, setSettings] = useState<BackgroundSettings>(DEFAULT_BACKGROUND_SETTINGS); const [uploaded, setUploaded] = useState<string | null>(null);
  const move = (offset: -1 | 1) => { const d = new Date(`${date}T00:00:00`); d.setDate(d.getDate() + offset); const nextDate = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`; router.push(`/calendar/${nextDate}`); };
  const d = new Date(`${date}T00:00:00`); const label = `${d.getFullYear()}年${d.getMonth() + 1}月${d.getDate()}日 · 星期${"日一二三四五六"[d.getDay()]}`;
  const upload = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; try { setUploaded(await fileToDataUrl(file)); setMessage("已上传，点击添加到日历"); } catch (error) { setMessage(error instanceof Error ? error.message : "上传失败"); } event.target.value = ""; };
  const save = async () => { if (!uploaded) { input.current?.click(); return; } try { const { outfit } = await apiFetch<{ outfit: { id: string } }>("/api/outfits", { method: "POST", body: JSON.stringify({ finalImage: uploaded }) }); await apiFetch("/api/calendar", { method: "POST", body: JSON.stringify({ outfitId: String(outfit.id), date, backgroundKey: settings.backgroundKey, backgroundImage: settings.backgroundImage, stickerScale: settings.stickerScale }) }); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "保存失败"); } };
  const transparentSticker = "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=";
  return <section className="calendar-detail empty-calendar-detail"><div className="calendar-detail-date"><button aria-label="前一天" onClick={() => move(-1)}><ChevronLeft /></button><strong>{label}</strong><button aria-label="后一天" onClick={() => move(1)}><ChevronRight /></button></div><div className="outfit-detail-layout"><div className="outfit-detail-stage"><StickerStage interactive containBackground sticker={uploaded ?? transparentSticker} settings={settings} onSettingsChange={setSettings}><BackgroundStepper value={settings} onChange={setSettings} /></StickerStage></div><aside className="outfit-detail-side"><div className="outfit-detail-actions"><button className="detail-side-btn" onClick={() => router.push("/calendar")}><ArrowLeft size={17} />返回</button><button className="detail-side-btn danger" disabled><Trash2 size={17} />删除</button><BackgroundPicker value={settings} onChange={setSettings} onUpload={() => input.current?.click()} /><button className="detail-side-btn" disabled={!uploaded} onClick={() => uploaded && window.open(uploaded, "_blank")}><Download size={17} />下载图片</button><button className="detail-side-btn" onClick={() => input.current?.click()}><Upload size={17} />上传新穿搭</button><button className="detail-side-btn primary" onClick={() => void save()}><CalendarPlus size={17} />添加到日历</button></div><input ref={input} hidden type="file" accept="image/*" onChange={upload} /><div className="outfit-originals">{uploaded && <div className="outfit-original-item"><img src={uploaded} alt="原始图片" /><span>原始图片</span></div>}</div>{message && <p className="result-message">{message}</p>}</aside></div></section>;
}
