"use client";
import { ArrowLeft, CalendarPlus, ChevronLeft, ChevronRight, Download, Trash2, Upload } from "lucide-react";
import { useRouter } from "next/navigation";
import { useRef, useState } from "react";
import { BackgroundPicker, BackgroundStepper, StickerStage } from "@/components/background/background-controls";
import { AddChoiceModal } from "@/components/modals/add-choice-modal";
import { StickerStage as WardrobeStage } from "@/components/background/background-controls";
import { apiFetch, fileToDataUrl } from "@/lib/client-api";
import { DEFAULT_BACKGROUND_SETTINGS, type BackgroundSettings } from "@/lib/backgrounds";

export function EmptyCalendarDetail({ date }: { date: string }) {
  const router = useRouter(); const input = useRef<HTMLInputElement>(null); const [message, setMessage] = useState(""); const [settings, setSettings] = useState<BackgroundSettings>(DEFAULT_BACKGROUND_SETTINGS); const [uploaded, setUploaded] = useState<string | null>(null); const [addOpen, setAddOpen] = useState(false); const [wardrobeOpen, setWardrobeOpen] = useState(false); const [wardrobe, setWardrobe] = useState<import("@/lib/types").Look[]>([]);
  const move = (offset: -1 | 1) => { const d = new Date(`${date}T00:00:00`); d.setDate(d.getDate() + offset); const nextDate = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`; router.push(`/calendar/${nextDate}`); };
  const d = new Date(`${date}T00:00:00`); const label = `${d.getFullYear()}年${d.getMonth() + 1}月${d.getDate()}日 · 星期${"日一二三四五六"[d.getDay()]}`;
  const upload = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; try { setUploaded(await fileToDataUrl(file)); setMessage("已上传，点击添加到日历"); } catch (error) { setMessage(error instanceof Error ? error.message : "上传失败"); } event.target.value = ""; };
  const save = async () => { if (!uploaded) { input.current?.click(); return; } try { const { outfit } = await apiFetch<{ outfit: { id: string } }>("/api/outfits", { method: "POST", body: JSON.stringify({ finalImage: uploaded }) }); await apiFetch("/api/calendar", { method: "POST", body: JSON.stringify({ outfitId: String(outfit.id), date, backgroundKey: settings.backgroundKey, backgroundImage: settings.backgroundImage, stickerScale: settings.stickerScale }) }); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "保存失败"); } };
  const openWardrobe = async () => { try { const data = await apiFetch<{ outfits: import("@/lib/types").Look[] }>("/api/outfits"); setWardrobe(data.outfits); setAddOpen(false); setWardrobeOpen(true); } catch (error) { setMessage(error instanceof Error ? error.message : "衣橱加载失败"); } };
  const chooseWardrobe = async (look: import("@/lib/types").Look) => { try { await apiFetch("/api/calendar", { method: "POST", body: JSON.stringify({ outfitId: String(look.id), date, backgroundImage: look.background, backgroundKey: look.backgroundKey, stickerScale: look.stickerScale }) }); setWardrobeOpen(false); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "添加失败"); } };
  const transparentSticker = "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=";
  return <section className="calendar-detail empty-calendar-detail"><div className="calendar-detail-date"><button aria-label="前一天" onClick={() => move(-1)}><ChevronLeft /></button><strong>{label}</strong><button aria-label="后一天" onClick={() => move(1)}><ChevronRight /></button></div><div className="outfit-detail-layout"><div className="outfit-detail-stage"><StickerStage interactive containBackground sticker={uploaded ?? transparentSticker} settings={settings} onSettingsChange={setSettings}><BackgroundStepper disabled={!uploaded} value={settings} onChange={setSettings} /></StickerStage></div><aside className="outfit-detail-side"><div className="outfit-detail-actions"><button className="detail-side-btn" onClick={() => router.push("/calendar")}><ArrowLeft size={17} />返回</button><button className="detail-side-btn danger" disabled><Trash2 size={17} />删除</button><BackgroundPicker disabled={!uploaded} value={settings} onChange={setSettings} onUpload={() => input.current?.click()} /><button className="detail-side-btn" disabled={!uploaded} onClick={() => uploaded && window.open(uploaded, "_blank")}><Download size={17} />下载图片</button><button className="detail-side-btn" onClick={() => setAddOpen(true)}><Upload size={17} />添加穿搭</button><button className="detail-side-btn primary" disabled={!uploaded} onClick={() => void save()}><CalendarPlus size={17} />添加到日历</button></div><input ref={input} hidden type="file" accept="image/*" onChange={upload} /><div className="outfit-originals">{uploaded && <div className="outfit-original-item"><img src={uploaded} alt="原始图片" /><span>原始图片</span></div>}</div>{message && <p className="result-message">{message}</p>}</aside></div>{addOpen && <AddChoiceModal close={() => setAddOpen(false)} startTry={() => router.push("/try")} uploadImage={(event) => { void upload(event); setAddOpen(false); }} chooseWardrobe={() => void openWardrobe()} />}{wardrobeOpen && <div className="overlay"><div className="choice-modal wardrobe-choice-modal"><button className="icon-close" aria-label="关闭" onClick={() => setWardrobeOpen(false)}>×</button><h2>从衣橱中选择</h2><div className="wardrobe-choice-grid">{wardrobe.length ? wardrobe.map((look) => <button className="wardrobe-choice-card" key={look.id} onClick={() => void chooseWardrobe(look)}><WardrobeStage containBackground trimSticker={false} sticker={look.sticker ?? look.image} settings={{ ...DEFAULT_BACKGROUND_SETTINGS, backgroundKey: look.backgroundKey ?? "none", backgroundImage: look.background }} /><span>{look.date}</span></button>) : <p>衣橱中暂无可用穿搭</p>}</div></div></div>}</section>;
}
