import React, {useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Upload, Sparkles, Shirt, CalendarDays, UserRound, ChevronRight, ChevronLeft, ChevronsLeft, ChevronsRight, Plus, Download, Trash2, X, Check, Search, ArrowLeft, ImagePlus, LogIn, RotateCcw} from 'lucide-react';
import './styles.css';

const looks = [
  {id:1, title:'城市周末', date:'2026年9月1日', image:'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=900&q=85', person:'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=400&q=80', garment:'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=400&q=80', background:'城市工作室'},
  {id:2, title:'柔软叠穿', date:'2026年8月28日', image:'https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=900&q=85', person:'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=400&q=80', garment:'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?auto=format&fit=crop&w=400&q=80', background:'保留原背景'},
  {id:3, title:'画廊午后', date:'2026年8月22日', image:'https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?auto=format&fit=crop&w=900&q=85', person:'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=400&q=80', garment:'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=400&q=80', background:'艺术画廊'},
];
const nav=[['try','试衣',Sparkles],['wardrobe','衣橱',Shirt],['calendar','日历',CalendarDays]];

function App(){
 const [page,setPage]=useState('try'); const [step,setStep]=useState(1); const [person,setPerson]=useState(null); const [garment,setGarment]=useState(null); const [background,setBackground]=useState(null); const [modal,setModal]=useState(null); const [selected,setSelected]=useState(null); const [result,setResult]=useState(false);
 const handleFile=(e,type)=>{const f=e.target.files?.[0]; if(!f)return; const u=URL.createObjectURL(f); if(type==='person')setPerson(u); else if(type==='garment')setGarment(u); else setBackground(u);};
 const canNext=step===1?person:garment;
 const reset=()=>{setStep(1);setPerson(null);setGarment(null);setBackground(null)};
 return <div className="app-shell">
  <header className="topbar"><div className="brand" onClick={()=>setPage('try')}><div className="brand-mark"><Sparkles size={17}/></div><span>fitcheck</span></div><div className="top-actions"><button className="profile-btn" onClick={()=>setModal('login')}><UserRound size={17}/><span>登录</span></button></div></header>
  <div className="body"><aside className="sidebar"><div className="side-label">工作区</div>{nav.map(([id,label,Icon])=><button key={id} className={'nav-item '+(page===id?'active':'')} onClick={()=>setPage(id)}><Icon size={18}/><span>{label}</span>{id==='wardrobe'&&<span className="nav-count">3</span>}</button>)}</aside>
   <main className="main-content">
    {page==='try'&&(result?<ResultPage person={person} garment={garment} setModal={setModal} back={()=>setResult(false)}/>:<TryPage {...{step,setStep,person,garment,background,handleFile,canNext,reset,generate:()=>setResult(true)}}/>)}
    {page==='wardrobe'&&<Wardrobe looks={looks} setSelected={setSelected} setPage={setPage} setModal={setModal}/>} 
    {page==='calendar'&&<Calendar looks={looks} setSelected={setSelected} setModal={setModal}/>} 
   </main>
  </div>
  {selected&&<Detail look={selected} close={()=>setSelected(null)} setModal={setModal}/>} {modal==='login'&&<Login close={()=>setModal(null)}/>} {modal==='add'&&<AddChoice close={()=>setModal(null)} startTry={()=>{setModal(null);setPage('try')}}/>}
 </div>
}

function UploadCard({kind,src,onChange}){return <label className={'upload-card '+(src?'filled':'')}><input type="file" accept="image/*" onChange={onChange}/>{src?<img src={src}/>:<><div className="upload-icon"><Upload size={20}/></div><span>{kind==='person'?'上传人物照片':kind==='garment'?'上传服装照片':'上传背景图片'}</span><small>JPG、PNG · 最大 5 MB</small></>}</label>}
function TryPage({step,setStep,person,garment,background,handleFile,canNext,reset,generate}){return <>
 <div className="try-layout"><section className={'workflow workflow-step-'+step}><div className="progress"><div className={'progress-step '+(step>=1?'done':'')}><span>01</span><b>人物</b></div><div className="progress-line"/><div className={'progress-step '+(step>=2?'done':'')}><span>02</span><b>服装</b></div><div className="progress-line"/><div className={'progress-step '+(step>=3?'done':'')}><span>03</span><b>背景</b></div></div>
   <div className="step-card"><div className="step-head"><div><h2>{step===1?'上传一张全身照':step===2?'上传一张服装照':'上传一张背景照'}</h2>{step===1&&<p>清晰、正面的照片能帮助我们更准确地完成试衣。</p>}{step===2&&<p>清晰、平铺的服装照片能帮助我们保留更多服装细节。</p>}{step===3&&<p>试试不同背景下的穿搭效果（默认保留原背景）。</p>}</div></div>
    {step===1&&<div className="single-preview guide-preview portrait-preview"><img src={person||'/default-person.png'} /></div>}
    {step===2&&<div className="single-preview guide-preview portrait-preview"><img src={garment||'/default-garment.png'} /></div>}
    {step===3&&<div className="single-preview guide-preview portrait-preview"><img src={background||'/default-background.png'} /></div>}
    <div className="step-actions step-actions-split">{step===1&&<label className="secondary-btn upload-action"><input type="file" accept="image/*" onChange={e=>handleFile(e,'person')}/>上传照片</label>}{step===2&&<label className="secondary-btn upload-action"><input type="file" accept="image/*" onChange={e=>handleFile(e,'garment')}/>上传照片</label>}{step===3&&<label className="secondary-btn upload-action"><input type="file" accept="image/*" onChange={e=>handleFile(e,'background')}/>上传照片</label>}<button className="primary-btn" disabled={!canNext&&step<3} onClick={()=>step<3?setStep(step+1):generate()}>{step<3?'下一步':'生成试衣效果'}</button></div>
   </div>
   <div className="workflow-foot"><span></span><button onClick={reset}>重新开始</button></div>
  </section></div>
 </>}

function ResultPage({setModal,back}){const resultImage=looks[0].image; return <div className="result-page"><div className="result-image"><img src={resultImage} alt="试衣结果" /></div><div className="result-actions"><a className="result-action primary" href={resultImage} download="fitcheck-result.jpg"><Download size={17}/>下载图片</a><button className="result-action" onClick={()=>setModal('login')}><Shirt size={17}/>保存到衣橱</button><button className="result-action" onClick={()=>setModal('login')}><CalendarDays size={17}/>添加到日历</button><button className="result-action" onClick={back}><RotateCcw size={17}/>重新生成</button></div></div>}

function Wardrobe({looks,setSelected,setPage,setModal}){return <><div className="look-grid"><button className="add-tile" onClick={()=>setModal('add')}><span><Plus size={22}/></span><b>添加新穿搭</b></button>{looks.map(l=><article className="look-card" key={l.id}><div className="look-image" onClick={()=>setSelected(l)}><img src={l.image}/><button className="card-delete" onClick={e=>{e.stopPropagation();setModal('delete')}}><Trash2 size={16}/></button><button className="card-detail" onClick={e=>{e.stopPropagation();setSelected(l)}}>展开详情</button></div></article>)}</div></>}
function Calendar({looks,setSelected,setModal}){const [cursor,setCursor]=useState(new Date(2026,8,1)); const year=cursor.getFullYear(); const month=cursor.getMonth(); const days=new Date(year,month+1,0).getDate(); const first=new Date(year,month,1).getDay(); const move=(delta)=>setCursor(new Date(year,month+delta,1)); const moveYear=(delta)=>setCursor(new Date(year+delta,month,1)); const lookFor=(day)=>year===2026&&month===8?(day===1?looks[0]:day===8?looks[1]:day===18?looks[2]:null):null; return <div className="calendar-page"><section className="calendar-card"><div className="calendar-title"><button aria-label="上一年" onClick={()=>moveYear(-1)}><ChevronsLeft size={15}/></button><button aria-label="上个月" onClick={()=>move(-1)}><ChevronLeft size={15}/></button><h2>{year}年{month+1}月</h2><button aria-label="下个月" onClick={()=>move(1)}><ChevronRight size={15}/></button><button aria-label="下一年" onClick={()=>moveYear(1)}><ChevronsRight size={15}/></button></div><div className="calendar-grid">{['日','一','二','三','四','五','六'].map(d=><div className="weekday" key={d}>{d}</div>)}{Array.from({length:first+days},(_,i)=>{const day=i<first?null:i-first+1;const look=day&&lookFor(day);return day?<button className={'day '+(look?'has-look':'')+(day===1&&year===2026&&month===8?' today':'')} key={i} onClick={()=>look?setSelected(look):setModal('add')}><span>{look?<img src={look.image}/>:day}</span>{look&&<small>{day}</small>}</button>:<div className="day-empty" key={i}/>})}</div></section></div>}
function Detail({look,close,setModal}){return <div className="overlay"><div className="detail-modal vertical"><div className="detail-top"><button onClick={close}><ArrowLeft size={18}/> 返回</button><button className="danger-btn" onClick={()=>setModal('delete')}><Trash2 size={17}/> 删除</button></div><div className="detail-image"><img src={look.image}/></div><div className="detail-content"><span className="detail-date">{look.date}</span><div className="source-row"><div><img src={look.person}/><small>人物</small></div><div><img src={look.garment}/><small>服装</small></div><div><div className="source-empty"><ImagePlus size={18}/></div><small>背景</small></div></div><div className="detail-actions"><button className="secondary-btn"><Download size={17}/> 下载</button><button className="primary-btn"><CalendarDays size={17}/> 添加到日历</button></div></div></div></div>}
function AddChoice({close,startTry}){return <div className="overlay"><div className="choice-modal"><button className="icon-close" onClick={close}><X size={19}/></button><h2>添加穿搭</h2><label className="choice-item"><input type="file" accept="image/*"/><ImagePlus size={22}/><div><b>上传图片</b><small>从本地选择一张图片</small></div><ChevronRight size={17}/></label><button className="choice-item" onClick={startTry}><Sparkles size={22}/><div><b>开始试衣</b><small>上传人物、服装和背景</small></div><ChevronRight size={17}/></button></div></div>}
function Login({close}){return <div className="overlay"><div className="login-modal"><button className="icon-close" onClick={close}><X size={19}/></button><div className="login-mark"><Sparkles size={19}/></div><h2>保存你的穿搭</h2><label>邮箱地址<input placeholder="you@example.com"/></label><label>密码<input type="password" placeholder="至少8个字符"/></label><button className="primary-btn login-btn" onClick={close}><LogIn size={17}/> 继续</button></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
